# Generated by Django 4.2.20 on 2025-03-19 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='Review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
