# Generated by Django 4.2.20 on 2025-03-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_alter_filme_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='TituloFilme',
            new_name='Titulo',
        ),
    ]
