# Generated by Django 4.2.20 on 2025-03-19 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_rename_titulofilme_filme_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='Review',
        ),
        migrations.CreateModel(
            name='FilmeAssistido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Analise', models.TextField(blank=True, null=True)),
                ('Titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filmes.filme')),
            ],
        ),
    ]
