# Generated by Django 4.2.20 on 2025-03-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_remove_filme_review_filmeassistido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='filmeassistido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
