# Generated by Django 4.2.20 on 2025-03-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_alter_filme_id_alter_filmeassistido_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filmeassistido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
