# Generated by Django 4.2.20 on 2025-03-21 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0006_alter_filme_id_alter_filmeassistido_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='Titulo',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='filmeassistido',
            old_name='Titulo',
            new_name='Tittle',
        ),
    ]
