# Generated by Django 4.2.20 on 2025-03-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0007_rename_titulo_filme_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmeassistido',
            old_name='Tittle',
            new_name='Title',
        ),
    ]
