# Generated by Django 4.2.20 on 2025-03-23 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0008_rename_tittle_filmeassistido_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilmeAssistido',
        ),
    ]
