# Generated by Django 4.2.20 on 2025-03-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0009_delete_filmeassistido'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='Watched',
            field=models.BooleanField(default=False),
        ),
    ]
